#!name=历史价格（京东比价）
#!desc=在京东商品标题处显示历史价格或查询状态。
#!homepage=https://github.com/YuXilong/surge-modules


[Script]
京东比价 = type=http-response,requires-body=1,max-size=0,timeout=20,pattern=^https?:\/\/api\.m\.jd\.com\/(client\.action|api)\?(?:[^#]*&)?functionId=(wareBusiness|serverConfig|basicConfig)(?:&|$),script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/main/js/vendor/deezertidal/jdprice.js?v=20260930-1

[MITM]
hostname = %APPEND% api.m.jd.com
