#!name=微博去广告

#!desc=微博去广告

[MITM]

hostname= %APPEND% api.weibo.cn, mapi.weibo.com, *.uve.weibo.com, new.vip.weibo.cn

[Script]

微博去广告=type=http-response,pattern=^https?://m?api\.weibo\.c(n|om)/2/(cardlist|searchall|page|messageflow|statuses/(unread_)?friends(/|_)timeline|groups/timeline|statuses/(unread_hot_timeline|extend|video_mixtimeline|container_timeline|repost_timeline)|profile/(me|statuses|container_timeline)|video/(community_tab|remind_info|tiny_stream_video_list)|checkin/show|\!/live/media_homelist|comments/build_comments|container/get_item|search/(finder|container_timeline|container_discover)),requires-body=1,max-size=2097152,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/main/js/weibo_main.js?v=20260930-1

微博去广告1=type=http-response,pattern=^https?://((sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad\.php|/wbapplua/wbpullad\.lua)|bootpreload\.uve\.weibo\.com/v2/ad/preload)(\?|$),requires-body=1,max-size=2097152,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/main/js/weibo_launch.js?v=20260930-1

微博去广告2=type=http-response,pattern=^https://api.weibo.cn/2/!/client/light_skin,requires-body=1,max-size=2097152,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/main/js/weibo_main.js?v=20260930-1

微博去广告3=type=http-response,pattern=^https://new.vip.weibo.cn/littleskin/preview,requires-body=1,max-size=2097152,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/main/js/weibo_main.js?v=20260930-1
