#!name=喜马拉雅无限畅听
#!desc=免费听时长改写，过滤开屏和首页广告。
#!author=yuxilong
#!category=实验
#!homepage=https://github.com/YuXilong/surge-modules

[Rule]
DOMAIN,adse.ximalaya.com,DIRECT
DOMAIN,adse.wsa.ximalaya.com,DIRECT
DOMAIN,ad-incentive.ximalaya.com,DIRECT

[URL Rewrite]
^(https:\/\/gslb(?:tx|ali)\.ximalaya\.com(?::443)?\/linkeye-cloud\/httpdns\/v3\/init\/\d+\?(?:(?!version=)[^&#]*&)*)version=[^&#]+((?:&(?!version=)[^&#]*)*)$ $1version=0e$2 header

[Script]
ximalaya-ads = type=http-response,pattern=^https?:\/\/(adse\.(wsa\.)?ximalaya\.com(?::(?:80|443))?\/(ting\/loading(\/ts-\d+)?|adx\/ad)|(mobile|mobilehera|mobwsa)\.ximalaya\.com(?::(?:80|443))?\/discovery-feed\/v4\/mix(\/ts-\d+)?)(\?[^#]*)?$,requires-body=1,max-size=2097152,timeout=10,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/9204dee5c6c2ea3510dfb08a2abec11c41ca00cb/js/ximalaya_ads.js?v=20260930-5
ximalaya-httpdns-sdk-response = type=http-response,pattern=^https:\/\/gslb(tx|ali)\.ximalaya\.com(?::443)?\/linkeye-cloud\/httpdns\/v3\/init\/\d+(\?[^#]*)?$,requires-body=1,max-size=1048576,timeout=10,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/9204dee5c6c2ea3510dfb08a2abec11c41ca00cb/js/ximalaya_httpdns.js?v=20260930-6
ximalaya-decrease-request = type=http-request,pattern=^https?:\/\/adse\.(wsa\.)?ximalaya\.com\/incentive\/ting\/decreaseDuration(\/ts-\d+)?(\?[^#]*)?$,requires-body=1,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/9204dee5c6c2ea3510dfb08a2abec11c41ca00cb/js/ximalaya_vip.js?v=20260930-2
ximalaya-sync-listen-request = type=http-request,pattern=^https?:\/\/ad-incentive\.ximalaya\.com\/incentive-sync\/ting\/welfare\/syncListenTime(\/ts-\d+)?(\?[^#]*)?$,requires-body=1,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/9204dee5c6c2ea3510dfb08a2abec11c41ca00cb/js/ximalaya_vip.js?v=20260930-2
ximalaya-free-listen = type=http-response,pattern=^https?:\/\/(adse\.(wsa\.)?ximalaya\.com\/incentive\/ting\/(currentDuration|decreaseDuration|rewardDuration|recAlbumInfo)|ad-incentive\.ximalaya\.com\/incentive-sync\/ting\/welfare\/syncListenTime)(\/ts-\d+)?(\?[^#]*)?$,requires-body=1,max-size=1048576,script-path=https://raw.githubusercontent.com/YuXilong/surge-modules/9204dee5c6c2ea3510dfb08a2abec11c41ca00cb/js/ximalaya_vip.js?v=20260930-2

[MITM]
hostname = %APPEND% adse.ximalaya.com, adse.wsa.ximalaya.com, ad-incentive.ximalaya.com, mobile.ximalaya.com, mobilehera.ximalaya.com, mobwsa.ximalaya.com, gslbtx.ximalaya.com, gslbali.ximalaya.com
